In [ ]:
import numpy as np 

# we are using 3 neurons for hidden layer which takes 
# A_T as input then computes A_T @ W and 
# then activation function and returns output 

A_T = np.array([
    [200, 17]
    ])

W = np.array([
    [1, -3, 5],
    [-2, 4, -6]
])

B = np.array([[-1, 1, 2]])

#Manual step by step implementation first then making the code modular
# print(A_T)
# print(W)
# print(B)

# Z = A_T @ W + B
# print(f"\nShape of Z is : {Z.shape} \nZ = {Z} \n")
# print(f"Z1_1 is : {Z[0][0]} \n")
# print(f"Z1_2 is : {Z[0][1]} \n")
# print(f"Z1_3 is : {Z[0][2]} \n")


[[200  17]]
[[ 1 -3  5]
 [-2  4 -6]]
[[-1  1  2]]

Shape of Z is : (1, 3) 
Z = [[ 165 -531  900]] 

Z1_1 is : 165 

Z1_2 is : -531 

Z1_3 is : 900 

