In [13]:
import numpy as np 

X = np.array([[1,2,3],[3,2,1]]) 
print(X)

X_T = X.T
print(X_T.shape) 

W = np.array([[1,2,3,4],[4,3,2,1]])
print(W.shape)

matrix_mul = X_T @ W
print(matrix_mul)
print(matrix_mul.shape)
#alternative way
matrix_mul_alter = np.matmul(X_T,W)
print(matrix_mul_alter)
print(matrix_mul_alter.shape)

[[1 2 3]
 [3 2 1]]
(3, 2)
(2, 4)
[[13 11  9  7]
 [10 10 10 10]
 [ 7  9 11 13]]
(3, 4)
[[13 11  9  7]
 [10 10 10 10]
 [ 7  9 11 13]]
(3, 4)
